"""empty message

Revision ID: 39d8d04a0b60
Revises: 
Create Date: 2020-07-25 00:57:24.237261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d8d04a0b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows', sa.PickleType(), nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.PickleType(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.PickleType(), nullable=True))
    op.add_column('venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.PickleType(), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'past_shows_count')
    op.drop_column('venue', 'past_shows')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'past_shows')
    # ### end Alembic commands ###
