"""empty message

Revision ID: a0d588a58a4c
Revises: 39d8d04a0b60
Create Date: 2020-07-25 01:59:40.828433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d588a58a4c'
down_revision = '39d8d04a0b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('show', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('show', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    op.add_column('show', sa.Column('venue_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'venue_name')
    op.drop_column('show', 'venue_image_link')
    op.drop_column('show', 'artist_name')
    op.drop_column('show', 'artist_image_link')
    # ### end Alembic commands ###
